In [1]:
# Programming for Data Analytics - TAMUSA
# Final Project (Titanic Survival) - Progress Report 2 
# Author - Jonathan Garcia
# In this project I will look through the data provided on Kaggle for the passengers of the Titanic and use it to determine 
# who suvived and who died
# This is a regression problem (binary - 0 or 1) 

In [44]:
# Data wrangling
import pandas as pd
import numpy as np

# Data visualisation
import seaborn as sns
import matplotlib.pyplot as plt
# Machine learning models
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# Remove warnings
import warnings
warnings.filterwarnings('ignore')

In [4]:
# it is important to understand the problem
# we will look at the relationship between variables in terms of survivability on the titanic


In [2]:
# Create a training and test set 
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
# this helps us understand the data by giving the column names and their data types
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [54]:
test.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Sex          418 non-null    object 
 3   Age          332 non-null    float64
 4   SibSp        418 non-null    int64  
 5   Parch        418 non-null    int64  
 6   Fare         417 non-null    float64
 7   Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 26.3+ KB


In [6]:
# display first ten rows of the training set 
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [7]:
# display the first 10 columns of the test set 
test.head(10)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0  34.5      0      0     330911   7.8292   NaN        Q  
1  47.0      1      0     363272   7.0000   NaN        S  
2  62.0      0      0     240276   9.6875   NaN        Q  
3  27.0      0      0     315154   8.6625   NaN        S  
4  22.0      1      1    3101298  12.2875   NaN        S  
5  14.0      0      0       7538   9.2250   NaN        S  
6  30.0      0      0     330972   7.6292   NaN        Q  
7  26.0      1      1     248738  29.0000   NaN        S  
8  18.0      0      0       2657   7.2292   NaN        C  
9  21.0      2      0  A/4 48871  24.1500   NaN        S

In [ ]:
# Data Description 
# Sirvided: 0 = Died, 1 = Survived 
# Pclass: 1= First Class, 2= 2nd Class, 3= 3rd Class (Proxy for socio-economic status)
# Sex: Male or female
# Age: Age in years (if less than one, fractional)
# SibSp: # of siblings or spouses aboard titanic
# Parch: # og parents or children aboard titanic
# Ticket: Passenger Ticket #
# Fare: Passenger Cost 
# Cabin: Cabin #
# Embarked: Passenger Embark Location; C: Cherbourg, Q: Queenstown, S= Southampton

In [4]:
# display the shape of our test and training data sets 
print("Training shape: ", train.shape)
print("Test shape ", test.shape)

Training shape:  (891, 12)
Test shape  (418, 11)


In [ ]:
# The training set has 891 rows and 12 columnss which are our independent variables
# the test set contains 418 rowss and 11 columns. The 12th is ommited because that is our target variable (Survived)

In [ ]:
# Now look at all variables that ar emissing values and fill missing values for better results

In [5]:
# display missing values in our dataset train 
missing_values = train.isnull().sum()

In [6]:
# display variables with missing values
print(missing_values[missing_values > 0])

Age         177
Cabin       687
Embarked      2
dtype: int64


In [62]:
# Drop variables, Name, Cabin and Ticket becuase these are similar to Sex, Pclass and Fare price. 
train = train.drop([ 'Embarked'], axis = 1)
test = test.drop(['Embarked'], axis = 1)

In [8]:
# creates a new column 'FamilySize' by adding 'SibSp' and 'Parch' together
train['FamilySize'] = train['SibSp'] + train['Parch']

In [9]:
# drops the original 'SibSp' and 'Parch' columns if needed
train = train.drop(['SibSp', 'Parch'], axis=1)

In [61]:
# display the updated DataFrame
print(train.head(10))

   PassengerId  Survived  Pclass        Age     Fare Embarked  FamilySize  \
0            1         0       3  22.000000   7.2500        S           1   
1            2         1       1  38.000000  71.2833        C           1   
2            3         1       3  26.000000   7.9250        S           0   
3            4         1       1  35.000000  53.1000        S           1   
4            5         0       3  35.000000   8.0500        S           0   
5            6         0       3  29.699118   8.4583        Q           0   
6            7         0       1  54.000000  51.8625        S           0   
7            8         0       3   2.000000  21.0750        S           4   
8            9         1       3  27.000000  11.1333        S           2   
9           10         1       2  14.000000  30.0708        C           1   

   male  
0     1  
1     0  
2     0  
3     0  
4     1  
5     1  
6     1  
7     1  
8     0  
9     0  


In [11]:
# calculate the mean age
mean_age = train['Age'].mean()

In [12]:
# fill missing ages with the median age
train['Age'].fillna(mean_age, inplace=True)

In [14]:
# Display the updated DataFrame
print(train.head(20))

    PassengerId  Survived  Pclass     Sex        Age     Fare Embarked  \
0             1         0       3    male  22.000000   7.2500        S   
1             2         1       1  female  38.000000  71.2833        C   
2             3         1       3  female  26.000000   7.9250        S   
3             4         1       1  female  35.000000  53.1000        S   
4             5         0       3    male  35.000000   8.0500        S   
5             6         0       3    male  29.699118   8.4583        Q   
6             7         0       1    male  54.000000  51.8625        S   
7             8         0       3    male   2.000000  21.0750        S   
8             9         1       3  female  27.000000  11.1333        S   
9            10         1       2  female  14.000000  30.0708        C   
10           11         1       3  female   4.000000  16.7000        S   
11           12         1       1  female  58.000000  26.5500        S   
12           13         0       3    m

In [15]:
# display variables with missing values
print(missing_values[missing_values > 0])

Age         177
Cabin       687
Embarked      2
dtype: int64


In [21]:
# create dummy variables for the 'Sex' column
train = pd.get_dummies(train, columns=['Sex'], prefix='', prefix_sep='')

In [68]:
# display the updated DataFrame
print(train.head())

   PassengerId  Survived  Pclass   Age     Fare  FamilySize  male
0            1         0       3  22.0   7.2500           1     1
1            2         1       1  38.0  71.2833           1     0
2            3         1       3  26.0   7.9250           0     0
3            4         1       1  35.0  53.1000           1     0
4            5         0       3  35.0   8.0500           0     1


In [23]:
# Amount of female and male passengers
train[['male', 'female']].sum()

male      577
female    314
dtype: int64

In [114]:
# drop the 'female' column
train = train.drop(['female'], axis=1)

KeyError: "['female'] not found in axis"

In [115]:
# display the updated DataFrame
print(train.head(25))

    PassengerId  Survived  Pclass        Age     Fare  FamilySize  male
0             1         0       3  22.000000   7.2500           1     1
1             2         1       1  38.000000  71.2833           1     0
2             3         1       3  26.000000   7.9250           0     0
3             4         1       1  35.000000  53.1000           1     0
4             5         0       3  35.000000   8.0500           0     1
5             6         0       3  29.699118   8.4583           0     1
6             7         0       1  54.000000  51.8625           0     1
7             8         0       3   2.000000  21.0750           4     1
8             9         1       3  27.000000  11.1333           2     0
9            10         1       2  14.000000  30.0708           1     0
10           11         1       3   4.000000  16.7000           2     0
11           12         1       1  58.000000  26.5500           0     0
12           13         0       3  20.000000   8.0500           

In [116]:
# display variables with missing values
print(missing_values[missing_values > 0])

Age         177
Cabin       687
Embarked      2
dtype: int64


In [26]:
# observing Pclass 
train['Pclass'].value_counts(dropna = False)

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [27]:
# Mean of survival by passenger class

train[['Pclass', 'Survived']].groupby(['Pclass'], as_index = False).mean().sort_values(by = 'Survived', ascending = False)

Pclass  Survived
0       1  0.629630
1       2  0.472826
2       3  0.242363

In [101]:
# Split data into features (X) and target variable (y)
X = train[['Age', 'FamilySize', 'Pclass', 'male']]
y = train['Survived']

In [124]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [125]:
logreg = LogisticRegression()

In [126]:
# Fit the model on the training data
logreg.fit(X_train, y_train)

LogisticRegression()

In [127]:
# Make predictions on the testing data
y_pred = logreg.predict(X_test)

In [128]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [129]:
# Print the results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.8212290502793296
Confusion Matrix:
 [[93 12]
 [20 54]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.89      0.85       105
           1       0.82      0.73      0.77        74

    accuracy                           0.82       179
   macro avg       0.82      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179



In [130]:

# Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
Y_pred = logreg.predict(X_test)
acc_log = round(logreg.score(X_train, y_train) * 100, 2)
acc_log


80.06

In [131]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [132]:
# Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)

# Decision Tree
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)
y_pred_decision_tree = decision_tree.predict(X_test)

# Random Forest
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
y_pred_random_forest = random_forest.predict(X_test)

# Support Vector Classifier (SVC)
svc = SVC()
svc.fit(X_train, y_train)
y_pred_svc = svc.predict(X_test)

In [148]:
# Evaluate the models
def evaluate_model(y_true, y_pred, model_name):
    accuracy = accuracy_score(y_true, y_pred)
    conf_matrix = confusion_matrix(y_true, y_pred)
    class_report = classification_report(y_true, y_pred)
    print(f"\n{model_name}:")
    print("\n")
    print("Accuracy:", accuracy)
    print("Confusion Matrix:\n", conf_matrix)
    print("Classification Report:\n", class_report)

# Evaluate Logistic Regression
evaluate_model(y_test, y_pred_logreg, "Logistic Regression")

# Evaluate Decision Tree
evaluate_model(y_test, y_pred_decision_tree, "Decision Tree")

# Evaluate Random Forest
evaluate_model(y_test, y_pred_random_forest, "Random Forest")

# Evaluate SVC
evaluate_model(y_test, y_pred_svc, "Support Vector Classifier")


Logistic Regression:


Accuracy: 0.8212290502793296
Confusion Matrix:
 [[93 12]
 [20 54]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.89      0.85       105
           1       0.82      0.73      0.77        74

    accuracy                           0.82       179
   macro avg       0.82      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179


Decision Tree:


Accuracy: 0.7877094972067039
Confusion Matrix:
 [[88 17]
 [21 53]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.84      0.82       105
           1       0.76      0.72      0.74        74

    accuracy                           0.79       179
   macro avg       0.78      0.78      0.78       179
weighted avg       0.79      0.79      0.79       179


Random Forest:


Accuracy: 0.8268156424581006
Confusion Matrix:
 [[92 13]
 [18 56]]
Classification Report:
              

In [149]:
# Evaluate Logistic Regression
evaluate_model(y_test, y_pred_logreg, "Logistic Regression")

# Evaluate Random Forest
evaluate_model(y_test, y_pred_random_forest, "Random Forest")



Logistic Regression:


Accuracy: 0.8212290502793296
Confusion Matrix:
 [[93 12]
 [20 54]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.89      0.85       105
           1       0.82      0.73      0.77        74

    accuracy                           0.82       179
   macro avg       0.82      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179


Random Forest:


Accuracy: 0.8268156424581006
Confusion Matrix:
 [[92 13]
 [18 56]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.88      0.86       105
           1       0.81      0.76      0.78        74

    accuracy                           0.83       179
   macro avg       0.82      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179



In [158]:
# Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

# Training accuracy
acc_train_logreg = round(logreg.score(X_train, y_train) * 100, 2)
print("Training Accuracy - Logistic Regression:", acc_train_logreg)

# Testing accuracy
acc_test_logreg = round(logreg.score(X_test, y_test) * 100, 2)
print("Testing Accuracy - Logistic Regression:", acc_test_logreg)
print("\n")

# Decision Tree
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)

# Training accuracy
acc_train_decision_tree = round(decision_tree.score(X_train, y_train) * 100, 2)
print("Training Accuracy - Decision Tree:", acc_train_decision_tree)

# Testing accuracy
acc_test_decision_tree = round(decision_tree.score(X_test, y_test) * 100, 2)
print("Testing Accuracy - Decision Tree:", acc_test_decision_tree)
print("\n")

# Random Forest
random_forest = RandomForestClassifier()
random_forest.fit(X_train, y_train)

# Training accuracy
acc_train_random_forest = round(random_forest.score(X_train, y_train) * 100, 2)
print("Training Accuracy - Random Forest:", acc_train_random_forest)

# Testing accuracy
acc_test_random_forest = round(random_forest.score(X_test, y_test) * 100, 2)
print("Testing Accuracy - Random Forest:", acc_test_random_forest)
print("\n")

# Support Vector Classifier
svc = SVC()
svc.fit(X_train, y_train)

# Training accuracy
acc_train_svc = round(svc.score(X_train, y_train) * 100, 2)
print("Training Accuracy - SVC:", acc_train_svc)

# Testing accuracy
acc_test_svc = round(svc.score(X_test, y_test) * 100, 2)
print("Testing Accuracy - SVC:", acc_test_svc)

Training Accuracy - Logistic Regression: 80.06
Testing Accuracy - Logistic Regression: 82.12


Training Accuracy - Decision Tree: 91.43
Testing Accuracy - Decision Tree: 78.77


Training Accuracy - Random Forest: 91.43
Testing Accuracy - Random Forest: 81.56


Training Accuracy - SVC: 64.89
Testing Accuracy - SVC: 60.89
